version: 2

sources:
    - name: jaffle_shop
      description: This is a replica of the Postgres database used by our app
      database: dbt_db
      schema: raw
      tables:
          - name: jaffle_shop_customers
            description: One record per customer.
          - name: jaffle_shop_orders
            description: One record per order. Includes cancelled and deleted orders.